import type { Component, Alert, HealthScore, Prediction, CorrelationGroup } from '../types'

export const mockComponents: Component[] = [
  {
    id: 'net-001',
    name: 'Main Load Balancer',
    type: 'network',
    status: 'healthy',
    health_score: 98,
    cpu: 12,
    memory: 28,
    disk: 5,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'net-002',
    name: 'Firewall Cluster',
    type: 'network',
    status: 'healthy',
    health_score: 96,
    cpu: 8,
    memory: 15,
    disk: 3,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'net-003',
    name: 'CDN Edge',
    type: 'network',
    status: 'healthy',
    health_score: 99,
    cpu: 5,
    memory: 12,
    disk: 2,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'app-001',
    name: 'User API',
    type: 'api',
    status: 'healthy',
    health_score: 95,
    cpu: 23,
    memory: 45,
    disk: 12,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'app-002',
    name: 'Payment Service',
    type: 'service',
    status: 'degraded',
    health_score: 72,
    cpu: 78,
    memory: 65,
    disk: 34,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'app-003',
    name: 'Auth Service',
    type: 'service',
    status: 'healthy',
    health_score: 99,
    cpu: 12,
    memory: 31,
    disk: 8,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'app-004',
    name: 'Order Service',
    type: 'service',
    status: 'healthy',
    health_score: 91,
    cpu: 35,
    memory: 52,
    disk: 18,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'app-005',
    name: 'Redis Cache',
    type: 'cache',
    status: 'healthy',
    health_score: 92,
    cpu: 15,
    memory: 38,
    disk: 5,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'app-006',
    name: 'Message Queue',
    type: 'queue',
    status: 'healthy',
    health_score: 97,
    cpu: 8,
    memory: 22,
    disk: 18,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'db-001',
    name: 'PostgreSQL Primary',
    type: 'database',
    status: 'healthy',
    health_score: 88,
    cpu: 42,
    memory: 67,
    disk: 55,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'db-002',
    name: 'PostgreSQL Replica',
    type: 'database',
    status: 'healthy',
    health_score: 94,
    cpu: 25,
    memory: 45,
    disk: 42,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'db-003',
    name: 'MongoDB Cluster',
    type: 'database',
    status: 'healthy',
    health_score: 91,
    cpu: 33,
    memory: 58,
    disk: 38,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'srv-001',
    name: 'APP-SRV-01',
    type: 'server',
    status: 'healthy',
    health_score: 96,
    cpu: 45,
    memory: 62,
    disk: 28,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'srv-002',
    name: 'APP-SRV-02',
    type: 'server',
    status: 'healthy',
    health_score: 94,
    cpu: 38,
    memory: 55,
    disk: 22,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'srv-003',
    name: 'DB-SRV-01',
    type: 'server',
    status: 'healthy',
    health_score: 97,
    cpu: 52,
    memory: 78,
    disk: 65,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'srv-004',
    name: 'DB-SRV-02',
    type: 'server',
    status: 'healthy',
    health_score: 95,
    cpu: 48,
    memory: 72,
    disk: 58,
    lastUpdated: new Date().toISOString(),
  },
]

export const mockAlerts: Alert[] = [
  {
    id: 'alert-001',
    title: 'High CPU Usage - Payment Service',
    description: 'Payment Service CPU usage has exceeded 75% threshold and is trending toward critical',
    severity: 'warning',
    status: 'active',
    componentId: 'app-002',
    componentName: 'Payment Service',
    timeToBreach: 45,
    confidenceInterval: { lower: 70, upper: 85 },
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'alert-002',
    title: 'Memory Pressure - PostgreSQL Primary',
    description: 'PostgreSQL memory usage approaching critical threshold within 2 hours',
    severity: 'warning',
    status: 'active',
    componentId: 'db-001',
    componentName: 'PostgreSQL Primary',
    timeToBreach: 120,
    confidenceInterval: { lower: 60, upper: 75 },
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'alert-003',
    title: 'Disk Space Warning',
    description: 'Database disk usage above 50%',
    severity: 'info',
    status: 'acknowledged',
    componentId: 'db-001',
    componentName: 'PostgreSQL Primary',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    acknowledgedAt: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'alert-004',
    title: 'Service Degraded - Payment Service',
    description: 'Payment Service health score dropped below 80%',
    severity: 'critical',
    status: 'active',
    componentId: 'app-002',
    componentName: 'Payment Service',
    createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: 'alert-005',
    title: 'API Response Time Increased',
    description: 'User API average response time above 500ms',
    severity: 'warning',
    status: 'resolved',
    componentId: 'app-001',
    componentName: 'User API',
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'alert-006',
    title: 'Connection Pool Exhaustion Risk',
    description: 'Database connection pool approaching capacity',
    severity: 'warning',
    status: 'active',
    componentId: 'db-001',
    componentName: 'PostgreSQL Primary',
    timeToBreach: 90,
    confidenceInterval: { lower: 75, upper: 90 },
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
]

export const mockHealthScore: HealthScore = {
  overall: 87,
  components: {
    healthy: 12,
    warning: 3,
    critical: 1,
    offline: 0,
  },
  total: 16,
  trend: Array.from({ length: 24 }, (_, i) => ({
    timestamp: new Date(Date.now() - (23 - i) * 60 * 60 * 1000).toISOString(),
    score: 80 + Math.random() * 15,
  })),
}

export const mockPredictions: Prediction[] = [
  {
    id: 'pred-001',
    componentId: 'app-002',
    componentName: 'Payment Service',
    metric: 'cpu',
    currentValue: 78,
    predictedValue: 92,
    timeToThreshold: 30,
    timeToBreach: 25,
    confidence: 85,
    threshold: 90,
    confidenceInterval: { lower: 68, upper: 92 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pred-002',
    componentId: 'db-001',
    componentName: 'PostgreSQL Primary',
    metric: 'memory',
    currentValue: 67,
    predictedValue: 85,
    timeToThreshold: 90,
    timeToBreach: 75,
    confidence: 78,
    threshold: 90,
    confidenceInterval: { lower: 60, upper: 88 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pred-003',
    componentId: 'srv-003',
    componentName: 'DB-SRV-01',
    metric: 'disk',
    currentValue: 65,
    predictedValue: 88,
    timeToThreshold: 180,
    timeToBreach: 150,
    confidence: 82,
    threshold: 90,
    confidenceInterval: { lower: 58, upper: 92 },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pred-004',
    componentId: 'app-002',
    componentName: 'Payment Service',
    metric: 'memory',
    currentValue: 65,
    predictedValue: 88,
    timeToThreshold: 60,
    timeToBreach: 45,
    confidence: 79,
    threshold: 90,
    confidenceInterval: { lower: 55, upper: 85 },
    createdAt: new Date().toISOString(),
  },
]

export const mockCorrelationGroups: CorrelationGroup[] = [
  {
    id: 'corr-001',
    name: 'Payment Service Cluster',
    components: ['app-002', 'db-001', 'app-006'],
    rootCause: 'Database connection pool exhaustion',
    blastRadius: 3,
  },
  {
    id: 'corr-002',
    name: 'API Gateway',
    components: ['app-001', 'app-003'],
    rootCause: 'Auth service latency',
    blastRadius: 2,
  },
  {
    id: 'corr-003',
    name: 'User Session Management',
    components: ['app-001', 'app-005', 'app-003'],
    rootCause: 'Cache memory pressure',
    blastRadius: 3,
  },
]